import { Order, Product } from './types';

export const plannerProducts: Product[] = [
  {
    id: 'planner-pipe-25',
    name: 'PE Rohr 25mm (Verlegeschlauch)',
    description: 'Hochwertiges PE-Rohr für die Haupt- und Zuleitung.',
    price: 1.50,
    category: 'Planer Artikel',
    imageUrl: 'https://images.unsplash.com/photo-1581092580497-e0d23cb61da8?q=80&w=400&auto=format&fit=crop',
    stock: 9999,
    articleNumber: 'PL-PIPE-25',
    metaTitle: 'PE Rohr 25mm',
    metaDescription: '',
    metaAdsText: '',
    variations: [],
    plannerType: 'pe_pipe'
  },
  {
    id: 'planner-drip-tube',
    name: 'Tropfschlauch XFD 16mm',
    description: 'Rainbird XFD 16mm, 33cm Tropfabstand, 2.3l/h',
    price: 1.20,
    category: 'Planer Artikel',
    imageUrl: 'https://images.unsplash.com/photo-1416879598555-2e6fb1ebd860?q=80&w=400&auto=format&fit=crop',
    stock: 9999,
    articleNumber: 'PL-DRIP-16',
    metaTitle: 'Tropfschlauch XFD',
    metaDescription: '',
    metaAdsText: '',
    variations: [],
    plannerType: 'drip_tube'
  },
  {
    id: 'planner-cable-3',
    name: 'Steuerkabel 3-adrig',
    description: 'Für bis zu 2 Stationen + Masse.',
    price: 1.80,
    category: 'Planer Artikel',
    imageUrl: 'https://images.unsplash.com/photo-1558449028-b53a39d100fc?q=80&w=400&auto=format&fit=crop',
    stock: 9999,
    articleNumber: 'PL-CBL-03',
    metaTitle: 'Steuerkabel 3',
    metaDescription: '',
    metaAdsText: '',
    variations: [],
    plannerType: 'cable',
    plannerWires: 3
  },
  {
    id: 'planner-cable-5',
    name: 'Steuerkabel 5-adrig',
    description: 'Für bis zu 4 Stationen + Masse.',
    price: 2.20,
    category: 'Planer Artikel',
    imageUrl: 'https://images.unsplash.com/photo-1558449028-b53a39d100fc?q=80&w=400&auto=format&fit=crop',
    stock: 9999,
    articleNumber: 'PL-CBL-05',
    metaTitle: 'Steuerkabel 5',
    metaDescription: '',
    metaAdsText: '',
    variations: [],
    plannerType: 'cable',
    plannerWires: 5
  },
  {
    id: 'planner-cable-7',
    name: 'Steuerkabel 7-adrig',
    description: 'Für bis zu 6 Stationen + Masse.',
    price: 2.80,
    category: 'Planer Artikel',
    imageUrl: 'https://images.unsplash.com/photo-1558449028-b53a39d100fc?q=80&w=400&auto=format&fit=crop',
    stock: 9999,
    articleNumber: 'PL-CBL-07',
    metaTitle: 'Steuerkabel 7',
    metaDescription: '',
    metaAdsText: '',
    variations: [],
    plannerType: 'cable',
    plannerWires: 7
  },
  {
    id: 'planner-cable-9',
    name: 'Steuerkabel 9-adrig',
    description: 'Für bis zu 8 Stationen + Masse.',
    price: 3.50,
    category: 'Planer Artikel',
    imageUrl: 'https://images.unsplash.com/photo-1558449028-b53a39d100fc?q=80&w=400&auto=format&fit=crop',
    stock: 9999,
    articleNumber: 'PL-CBL-09',
    metaTitle: 'Steuerkabel 9',
    metaDescription: '',
    metaAdsText: '',
    variations: [],
    plannerType: 'cable',
    plannerWires: 9
  },
  {
    id: 'planner-cable-13',
    name: 'Steuerkabel 13-adrig',
    description: 'Für bis zu 12 Stationen + Masse.',
    price: 4.50,
    category: 'Planer Artikel',
    imageUrl: 'https://images.unsplash.com/photo-1558449028-b53a39d100fc?q=80&w=400&auto=format&fit=crop',
    stock: 9999,
    articleNumber: 'PL-CBL-13',
    metaTitle: 'Steuerkabel 13',
    metaDescription: '',
    metaAdsText: '',
    variations: [],
    plannerType: 'cable',
    plannerWires: 13
  },
  {
    id: 'planner-valve-box',
    name: 'Verteilerbox (leer)',
    description: 'Schacht für Magnetventile',
    price: 45.00,
    category: 'Planer Artikel',
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=400&auto=format&fit=crop',
    stock: 9999,
    articleNumber: 'PL-VBOX-01',
    metaTitle: 'Verteilerbox',
    metaDescription: '',
    metaAdsText: '',
    variations: [],
    plannerType: 'valve_box'
  },
  {
    id: 'planner-valve',
    name: 'Magnetventil 24V AC',
    description: 'Zuverlässiges Magnetventil für jede Beregnungszone',
    price: 24.90,
    category: 'Planer Artikel',
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=400&auto=format&fit=crop',
    stock: 9999,
    articleNumber: 'PL-VLV-01',
    metaTitle: 'Magnetventil',
    metaDescription: '',
    metaAdsText: '',
    variations: [],
    plannerType: 'valve'
  },
  {
    id: 'planner-sprinkler',
    name: 'Sprüh-/Getrieberegner Set',
    description: 'Kompletter Regner inkl. Gehäuse und Düse.',
    price: 18.50,
    category: 'Planer Artikel',
    imageUrl: 'https://images.unsplash.com/photo-1585074245728-eeecc3fcbdd3?q=80&w=400&auto=format&fit=crop',
    stock: 9999,
    articleNumber: 'PL-SPR-01',
    metaTitle: 'Sprühregner',
    metaDescription: '',
    metaAdsText: '',
    variations: [],
    plannerType: 'sprinkler'
  },
  {
    id: 'planner-controller',
    name: 'Steuergerät',
    description: 'Intelligentes Steuergerät inkl. WLAN.',
    price: 129.90,
    category: 'Planer Artikel',
    imageUrl: 'https://images.unsplash.com/photo-1558449028-b53a39d100fc?q=80&w=400&auto=format&fit=crop',
    stock: 9999,
    articleNumber: 'PL-CTRL-01',
    metaTitle: 'Steuergerät',
    metaDescription: '',
    metaAdsText: '',
    variations: [],
    plannerType: 'controller',
    plannerStations: 6
  },
  {
    id: 'planner-fittings',
    name: 'Standard Fitting Set',
    description: 'Pauschale für Abzweige, T-Stücke und Winkel pro Zone/Regner',
    price: 12.00,
    category: 'Planer Artikel',
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=400&auto=format&fit=crop',
    stock: 9999,
    articleNumber: 'PL-FIT-01',
    metaTitle: 'Fitting Set',
    metaDescription: '',
    metaAdsText: '',
    variations: [],
    plannerType: 'fitting'
  },
  // Vormontierte Einheiten (1 bis 10 Stationen)
  {
    id: 'planner-asb-1',
    name: 'Verteilerbox (1 Station, 2x Magnetventil)',
    description: 'Vormontierte Verteilerbox inklusive Controller (Steuergerät), Verbindungsteilen und 2 Magnetventilen (1 Zone + 1 Hauptventil). Anschlussfertig montiert.',
    price: 199.90,
    category: 'Planer Artikel',
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=400&auto=format&fit=crop',
    stock: 9999,
    articleNumber: 'PL-ASB-01',
    metaTitle: 'Verteilerbox 1 Station',
    metaDescription: '',
    metaAdsText: '',
    variations: [],
    plannerType: 'assembled_box',
    plannerStations: 1
  },
  {
    id: 'planner-asb-2',
    name: 'Verteilerbox (2 Stationen, 3x Magnetventil)',
    description: 'Vormontierte Verteilerbox inklusive Controller (Steuergerät), Verbindungsteilen und 3 Magnetventilen (2 Zonen + 1 Hauptventil). Anschlussfertig montiert.',
    price: 259.90,
    category: 'Planer Artikel',
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=400&auto=format&fit=crop',
    stock: 9999,
    articleNumber: 'PL-ASB-02',
    metaTitle: 'Verteilerbox 2 Stationen',
    metaDescription: '',
    metaAdsText: '',
    variations: [],
    plannerType: 'assembled_box',
    plannerStations: 2
  },
  {
    id: 'planner-asb-3',
    name: 'Verteilerbox (3 Stationen, 4x Magnetventil)',
    description: 'Vormontierte Verteilerbox inklusive Controller (Steuergerät), Verbindungsteilen und 4 Magnetventilen (3 Zonen + 1 Hauptventil). Anschlussfertig montiert.',
    price: 319.90,
    category: 'Planer Artikel',
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=400&auto=format&fit=crop',
    stock: 9999,
    articleNumber: 'PL-ASB-03',
    metaTitle: 'Verteilerbox 3 Stationen',
    metaDescription: '',
    metaAdsText: '',
    variations: [],
    plannerType: 'assembled_box',
    plannerStations: 3
  },
  {
    id: 'planner-asb-4',
    name: 'Verteilerbox (4 Stationen, 5x Magnetventil)',
    description: 'Vormontierte Verteilerbox inklusive Controller (Steuergerät), Verbindungsteilen und 5 Magnetventilen (4 Zonen + 1 Hauptventil). Anschlussfertig montiert.',
    price: 379.90,
    category: 'Planer Artikel',
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=400&auto=format&fit=crop',
    stock: 9999,
    articleNumber: 'PL-ASB-04',
    metaTitle: 'Verteilerbox 4 Stationen',
    metaDescription: '',
    metaAdsText: '',
    variations: [],
    plannerType: 'assembled_box',
    plannerStations: 4
  },
  {
    id: 'planner-asb-5',
    name: 'Verteilerbox (5 Stationen, 6x Magnetventil)',
    description: 'Vormontierte Verteilerbox inklusive Controller (Steuergerät), Verbindungsteilen und 6 Magnetventilen (5 Zonen + 1 Hauptventil). Anschlussfertig montiert.',
    price: 439.90,
    category: 'Planer Artikel',
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=400&auto=format&fit=crop',
    stock: 9999,
    articleNumber: 'PL-ASB-05',
    metaTitle: 'Verteilerbox 5 Stationen',
    metaDescription: '',
    metaAdsText: '',
    variations: [],
    plannerType: 'assembled_box',
    plannerStations: 5
  },
  {
    id: 'planner-asb-6',
    name: 'Verteilerbox (6 Stationen, 7x Magnetventil)',
    description: 'Vormontierte Verteilerbox inklusive Controller (Steuergerät), Verbindungsteilen und 7 Magnetventilen (6 Zonen + 1 Hauptventil). Anschlussfertig montiert.',
    price: 499.90,
    category: 'Planer Artikel',
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=400&auto=format&fit=crop',
    stock: 9999,
    articleNumber: 'PL-ASB-06',
    metaTitle: 'Verteilerbox 6 Stationen',
    metaDescription: '',
    metaAdsText: '',
    variations: [],
    plannerType: 'assembled_box',
    plannerStations: 6
  },
  {
    id: 'planner-asb-7',
    name: 'Verteilerbox (7 Stationen, 8x Magnetventil)',
    description: 'Vormontierte Verteilerbox inklusive Controller (Steuergerät), Verbindungsteilen und 8 Magnetventilen (7 Zonen + 1 Hauptventil). Anschlussfertig montiert.',
    price: 559.90,
    category: 'Planer Artikel',
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=400&auto=format&fit=crop',
    stock: 9999,
    articleNumber: 'PL-ASB-07',
    metaTitle: 'Verteilerbox 7 Stationen',
    metaDescription: '',
    metaAdsText: '',
    variations: [],
    plannerType: 'assembled_box',
    plannerStations: 7
  },
  {
    id: 'planner-asb-8',
    name: 'Verteilerbox (8 Stationen, 9x Magnetventil)',
    description: 'Vormontierte Verteilerbox inklusive Controller (Steuergerät), Verbindungsteilen und 9 Magnetventilen (8 Zonen + 1 Hauptventil). Anschlussfertig montiert.',
    price: 619.90,
    category: 'Planer Artikel',
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=400&auto=format&fit=crop',
    stock: 9999,
    articleNumber: 'PL-ASB-08',
    metaTitle: 'Verteilerbox 8 Stationen',
    metaDescription: '',
    metaAdsText: '',
    variations: [],
    plannerType: 'assembled_box',
    plannerStations: 8
  },
  {
    id: 'planner-asb-9',
    name: 'Verteilerbox (9 Stationen, 10x Magnetventil)',
    description: 'Vormontierte Verteilerbox inklusive Controller (Steuergerät), Verbindungsteilen und 10 Magnetventilen (9 Zonen + 1 Hauptventil). Anschlussfertig montiert.',
    price: 679.90,
    category: 'Planer Artikel',
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=400&auto=format&fit=crop',
    stock: 9999,
    articleNumber: 'PL-ASB-09',
    metaTitle: 'Verteilerbox 9 Stationen',
    metaDescription: '',
    metaAdsText: '',
    variations: [],
    plannerType: 'assembled_box',
    plannerStations: 9
  },
  {
    id: 'planner-asb-10',
    name: 'Verteilerbox (10 Stationen, 11x Magnetventil)',
    description: 'Vormontierte Verteilerbox inklusive Controller (Steuergerät), Verbindungsteilen und 11 Magnetventilen (10 Zonen + 1 Hauptventil). Anschlussfertig montiert.',
    price: 739.90,
    category: 'Planer Artikel',
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=400&auto=format&fit=crop',
    stock: 9999,
    articleNumber: 'PL-ASB-10',
    metaTitle: 'Verteilerbox 10 Stationen',
    metaDescription: '',
    metaAdsText: '',
    variations: [],
    plannerType: 'assembled_box',
    plannerStations: 10
  },
  {
    id: 'planner-soft-pipe-16',
    name: 'PE-Rohr weich 16mm (Zuleitung zu Tropfschlauch)',
    description: 'Weiches und flexibles PE-Rohr PN10 16mm zur Speisung der Tropfabgänge.',
    price: 0.90,
    category: 'Planer Artikel',
    imageUrl: 'https://images.unsplash.com/photo-1581092580497-e0d23cb61da8?q=80&w=400&auto=format&fit=crop',
    stock: 9999,
    articleNumber: 'PL-PIPE-SOFT-16',
    metaTitle: 'PE Rohr weich 16mm',
    metaDescription: '',
    metaAdsText: '',
    variations: [],
    plannerType: 'soft_pipe'
  },
  {
    id: 'planner-connector-25-16',
    name: 'Verbinder PE-Rohr 25mm x PE-Rohr weich 16mm',
    description: 'Druckfester Spezialverbinder für den Übergang von Haupt- zu Weichleitung.',
    price: 3.50,
    category: 'Planer Artikel',
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=400&auto=format&fit=crop',
    stock: 9999,
    articleNumber: 'PL-CONN-25-16',
    metaTitle: 'Verbinder 25 x 16',
    metaDescription: '',
    metaAdsText: '',
    variations: [],
    plannerType: 'connector_25_16'
  },
  {
    id: 'planner-elbow-25-12',
    name: 'Klemmverschraubung Winkel 25mm x 1/2" Innengewinde',
    description: 'Robuste Winkelverschraubung für das Rohrende vor dem Regneranschluß.',
    price: 4.50,
    category: 'Planer Artikel',
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=400&auto=format&fit=crop',
    stock: 9999,
    articleNumber: 'PL-FITTING-ELBOW-25',
    metaTitle: 'Winkelverschraubung 25 x 1/2 IG',
    metaDescription: '',
    metaAdsText: '',
    variations: [],
    plannerType: 'elbow_25_12'
  },
  {
    id: 'planner-t-piece-25-12-25',
    name: 'Klemmverschraubung T-Stück 25mm x 1/2" Innengewinde x 25mm',
    description: 'Verteiler-T-Stück für Regneranschlüsse in Leitungsmitte.',
    price: 5.90,
    category: 'Planer Artikel',
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=400&auto=format&fit=crop',
    stock: 9999,
    articleNumber: 'PL-FITTING-TPE-25',
    metaTitle: 'T-Stück 25 x 1/2 IG x 25',
    metaDescription: '',
    metaAdsText: '',
    variations: [],
    plannerType: 't_piece_25_12_25'
  },
  {
    id: 'planner-swing-joint',
    name: 'Swing Joint 1/2" Aussengewinde x 1/2" Aussengewinde',
    description: 'Flexibles Anschlussgelenk für Regner um mechanische Belastungen abzufedern.',
    price: 6.50,
    category: 'Planer Artikel',
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=400&auto=format&fit=crop',
    stock: 9999,
    articleNumber: 'PL-SWING-JT',
    metaTitle: 'Swing Joint 1/2',
    metaDescription: '',
    metaAdsText: '',
    variations: [],
    plannerType: 'swing_joint'
  },
  {
    id: 'planner-sprinkler-body',
    name: 'Hunter Pro-Spray PRS40 Gehäuse',
    description: 'Druckreguliertes High-End-Regnergehäuse für konstante 2,8 bar Düsenspeisung.',
    price: 14.90,
    category: 'Planer Artikel',
    imageUrl: 'https://images.unsplash.com/photo-1585074245728-eeecc3fcbdd3?q=80&w=400&auto=format&fit=crop',
    stock: 9999,
    articleNumber: 'PL-SPR-PRS40',
    metaTitle: 'Hunter Pro-Spray PRS40',
    metaDescription: '',
    metaAdsText: '',
    variations: [],
    plannerType: 'sprinkler_body'
  },
  {
    id: 'planner-rzws',
    name: 'Hunter RZWS Wurzelbewässerung',
    description: 'Unterirdisches Wurzelbewässerungssystem (Gießzylinder RZWS) zur Versorgung von Baumwurzeln.',
    price: 29.90,
    category: 'Planer Artikel',
    imageUrl: 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?q=80&w=400&auto=format&fit=crop',
    stock: 9999,
    articleNumber: 'PL-RZWS',
    metaTitle: 'Hunter RZWS Wurzelbewässerung',
    metaDescription: '',
    metaAdsText: '',
    variations: [],
    plannerType: 'rzws'
  },
  {
    id: 'planner-pressure-reducer',
    name: 'Druckminderer für Kleingärten (3/4" Gewinde)',
    description: 'Druckminderer zur automatischen Reduzierung des Eingangsdrucks zum Schutz von Tropfschläuchen und Kleinsystemen.',
    price: 19.90,
    category: 'Planer Artikel',
    imageUrl: 'https://images.unsplash.com/photo-1581094288338-2314dddb7eed?q=80&w=400&auto=format&fit=crop',
    stock: 9999,
    articleNumber: 'PL-PR-REDUCER',
    metaTitle: 'Druckminderer',
    metaDescription: 'Druckminderer zur Druckreduzierung in Kleingärten',
    metaAdsText: '',
    variations: [],
    plannerType: 'pressure_reducer'
  }
];

export const initialProducts: Product[] = [];

export const initialOrders: Order[] = [];
